---
- name: install_gearman
  yum: name='gearmand' state='present'

- name: install libgearman
  yum: name='libgearman' state='present'

- name: install mod_gearman
  yum: name="https://houston.csc.fi/pub/rpm/el7/mod_gearman2-2.1.5_opsview201310-3.el7.csc.x86_64.rpm" state='present'

