---
- name: install_gearman
  yum: name='gearmand' state='present'

- name: install libgearman
  yum: name='libgearman' state='present'

- name: start gearmand
  service: name=gearmand state=started enabled=yes

- name: copy mod_gearman2 rpm 
  copy: src=files/mod_gearman2-2.1.5_opsview201310-3.el7.csc.x86_64.rpm dest=/tmp/mod_gearman2-2.1.5_opsview201310-3.el7.csc.x86_64.rpm

- name: install mod_gearman
  yum: name="/tmp/mod_gearman2-2.1.5_opsview201310-3.el7.csc.x86_64.rpm" state='present'

- name: copy mod_gearman_worker.conf
  template: src=mod_gearman2_worker.conf.j2 dest=/etc/mod_gearman2/mod_gearman2_worker.conf

- name: Create nagios checks directory
  file: path=/usr/local/nagios/ state=directory recurse=yes force=yes
  run_once: true

- name: Does nagios plugin dir exist?
  stat: path=/usr/lib64/nagios/plugins
  register: reg_gearman_nagios_plugin_dir
  changed_when: False
  ignore_errors: True

- name: Create symlinks
  file: path=/usr/local/nagios/libexec src=/usr/lib64/nagios/plugins state=link 
  run_once: true
  when: reg_gearman_nagios_plugin_dir is defined and reg_gearman_nagios_plugin_dir.stat.exists

- name: Start mod_gearman2_worker service
  service: name=mod-gearman2-worker state=started enabled=yes
